/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDoApp;

public class Main {

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
